version: '3.9'

services:
  registration:
    container_name: twake-matrix-register
    build: .
    ports:
      - 8080:3000
    env_file:
      - .env
    networks:
      - registration-network
  openldap:
    image: bitnami/openldap
    ports:
      - '1389:1389'
      - '1636:1636'
    env_file:
      - .env
    volumes:
      - openldap_data:/bitnami/openldap
    networks:
      - registration-network

networks:
  registration-network:
    driver: bridge

volumes:
  openldap_data:
    driver: local
